apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: okta-tap-test
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: okta-tap-test
spec:
  source:
    git:
      url: https://github.com/trevorputbrese/okta-tap-test
      ref:
        branch: main
