apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: python-polling-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: python-polling-app
spec:
  source:
    git:
      url: https://github.com/trevorputbrese/python-polling-app
      ref:
        branch: main
